version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encinitas-collector-go
    environment:
      REDIS_ADDR: localhost:6379
      REDIS_PASS:
      REDIS_DB:
      POSTGRES_HOST: 100.71.248.65
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: solana
      INFLUXDB_URL: http://localhost:8086
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
    image: 017128164736.dkr.ecr.eu-west-1.amazonaws.com/encinitas-collector-go:dev
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: encinitas-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  influxdb:
    image: influxdb:2.0
    container_name: encinitas-influxdb
    volumes:
      - influxdb-volume:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: influxdb
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASS}
      DOCKER_INFLUXDB_INIT_ORG: encinitas
      DOCKER_INFLUXDB_INIT_BUCKET: encinitas_metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    ports:
      - "8086:8086"
    restart: unless-stopped

volumes:
  influxdb-volume:

