version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encinitas-collector-go
    environment:
      REDIS_ADDR: 100.116.116.76:6379
      REDIS_PASS: ${REDIS_PASS}
      REDIS_DB: 0
      POSTGRES_HOST: 100.107.126.77
      POSTGRES_PORT: 5432
      POSTGRES_USER: solana
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: solana
      INFLUXDB_URL: http://100.116.116.76:8086
      INFLUXDB_TELEGRAF_URL: http://100.116.116.76:8087/metrics
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
    image: 017128164736.dkr.ecr.eu-west-1.amazonaws.com/encinitas-collector-go:dev
    network_mode: host
    restart: unless-stopped
