version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encinitas-collector-go
    environment:
      REDIS_ADDR: localhost:6379
      REDIS_PASS:
      REDIS_DB:
      POSTGRES_HOST: 100.71.248.65
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: solana
    image: 017128164736.dkr.ecr.eu-west-1.amazonaws.com/encinitas-collector-go:dev
    # I'm using the host network to have access to my VPN resources
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: encinitas-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

# The custom network is no longer needed since we are using the host network for the app.
# networks:
#   encinitas_collector_go:
