image:
  repository: 017128164736.dkr.ecr.eu-west-1.amazonaws.com/encinitas-collector-go
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: sales-ai-pre.bysidecar.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-sales-ai-pre-bysidecar-me
      hosts:
        - sales-ai-pre.bysidecar.me
env:
- name: REDIS_ADDR
  value: ""
- name: REDIS_PASS
  value: ""
- name: REDIS_DB
  value: 0

autoscaling:
  enabled: false
serviceAccount:
  create: false
resources: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
