image:
  repository: 017128164736.dkr.ecr.eu-west-1.amazonaws.com/encinitas-collector-go
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

env:
- name: REDIS_ADDR
  value: "redis-master.encinitas.svc.cluster.local:6379"
- name: REDIS_PASS
  value: "zAFR1Y2emC"
- name: REDIS_DB
  value: "0"
- name: POSTGRES_HOST
  value: "100.71.248.65"
- name: POSTGRES_PORT
  value: "5432"
- name: POSTGRES_USER
  valueFrom:
    secretKeyRef:
      name: postgres
      key: user
- name: POSTGRES_PASS
  valueFrom:
    secretKeyRef:
      name: postgres
      key: pass
- name: POSTGRES_DB
  value: solana
- name: INFLUXDB_URL
  value: http://influx:8086
- name: INFLUXDB_TOKEN
  valueFrom:
    secretKeyRef:
      name: influx
      key: token

autoscaling:
  enabled: false
serviceAccount:
  create: false
resources: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
